import {addPart,rollFreshPart,grantCarShards} from './progression.js';
import {blueprintWord} from './car-levels.js';
export const BONUS_STEPS=[{score:800,cash:300,scrap:15,shards:1,rarity:null,name:'БРОНЗА'},{score:2000,cash:650,scrap:35,shards:2,rarity:1,name:'СЕРЕБРО'},{score:4000,cash:1100,scrap:65,shards:4,rarity:2,name:'ЗОЛОТО'}];
const tickets=[{rank:90,map:5,name:'Гребень'},{rank:135,map:6,name:'Перекладки'},{rank:180,map:8,name:'Сосновый бор'},{rank:225,map:7,name:'Парковка'}];
export const availableDriftBonuses=s=>tickets.map(t=>({...t,key:`${s.campaignChampionships||0}:${t.rank}`})).filter(t=>s.rank>=t.rank&&!s.driftBonusClaims?.includes(t.key));
export const driftPrizeTier=score=>BONUS_STEPS.filter(t=>score>=t.score).at(-1)||null;
export function rewardDriftBonus(s,key,score,{finished=true,rng=Math.random}={}){const ticket=availableDriftBonuses(s).find(t=>t.key===key),tier=driftPrizeTier(score),empty={cash:0,scrap:0,hard:0,crates:[],claimed:false};if(!ticket||!tier||!finished)return empty;const drop=tier.rarity===null?null:addPart(s,rollFreshPart(s,tier.rarity,rng)),carShard=grantCarShards(s,tier.shards),convertedShards=tier.shards-(carShard?.amount||0),scrap=tier.scrap+convertedShards*10;s.cash+=tier.cash;s.scrap+=scrap;(s.driftBonusClaims??=[]).push(key);s.races++;return {...empty,cash:tier.cash,scrap,convertedShards,drop,carShard,tier:tier.name,claimed:true};}
export function rewardDriftPractice(s,score){const tier=driftPrizeTier(score),cash=tier?Math.round(tier.cash*.25):50,scrap=tier?Math.round(tier.scrap*.25):3;s.cash+=cash;s.scrap+=scrap;s.races++;return {cash,scrap,hard:0,crates:[]};}
export const bonusLadder=()=>`<div class="bonus-ladder">${BONUS_STEPS.map(t=>`<div><b>${t.score.toLocaleString('ru-RU')} ОЧКОВ</b><span>${t.cash} ₽ · ${t.scrap} ⚒ · ${t.shards} ${blueprintWord(t.shards)}${t.rarity!==null?'<br>'+ (t.rarity===2?'Эпическая+':'Редкая+')+' деталь':''}</span></div>`).join('')}</div><p class="route-note">Один набор за лучший достигнутый порог в этом заезде. До 800 очков — повторная попытка. Лишние чертежи → материалы. Бонус можно отложить.</p>`;
export function bonusInvites(s){const list=availableDriftBonuses(s);return list.length?`<section class="bonus-invites"><small>БОНУС ПОСЛЕ БОССА · ${list.length}</small><h3>ЕЩЁ ДОБЫЧА</h3><p>Необязательно для кампании. Чем больше очков, тем богаче награда.</p>${list.map(t=>`<button class="secondary" data-bonus-drift="${t.key}">${t.name} · район ${t.rank/45} <span>↗</span></button>`).join('')}${bonusLadder()}</section>`:'';}
