import {openDialog,closeDialog} from './motion.js';
import {CARS} from './fleet.js';
import {normalizeDuelBuild,duelClassFor} from './duel-rules.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path='',body)=>{const r=await fetch('/api/duels'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});if(!r.headers.get('content-type')?.includes('json'))throw Error('Дуэли сейчас недоступны');const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'Не удалось связаться с сервером'),{code:d.code});return d;};
export function bindDuels({startRace,getBuild,toast}){
 const dialog=document.createElement('dialog');dialog.id='duel-dialog';dialog.className='meta-dialog';dialog.innerHTML='<header class="meta-header"><h2>ДУЭЛИ</h2><button class="icon-button" data-close aria-label="Закрыть">✕</button></header><div class="duel-body"></div>';document.body.append(dialog);const body=dialog.querySelector('.duel-body');let busy=false,data=null,pendingMemory=null;
 const readPending=()=>{if(pendingMemory)return pendingMemory;try{return JSON.parse(localStorage.getItem('rayon-duel-pending')||'null');}catch{return null;}};
 function clearPending(ticket){if(readPending()?.ticket!==ticket)return;pendingMemory=null;try{localStorage.removeItem('rayon-duel-pending');}catch{}}
 async function flush(){const p=readPending();if(!p)return null;try{const r=await api('/finish',p);clearPending(p.ticket);return r.result;}catch(e){if(['expired_ticket','closed_ticket','invalid_replay'].includes(e.code))clearPending(p.ticket);throw e;}}
 async function open(){openDialog(dialog);body.innerHTML='<p class="event-empty">Ищем гонщиков…</p>';try{data=await api();render();}catch(e){body.innerHTML='<p class="event-empty">'+esc(e.message)+'</p><button class="primary" data-retry>ПОВТОРИТЬ</button>';}}
 function render(){const p=data.profile,build=normalizeDuelBuild(getBuild()),car=CARS[build.car],cls=duelClassFor(build.power);body.innerHTML=`<div class="race-modes"><button data-campaign>КАМПАНИЯ</button><button class="active" aria-pressed="true">ДУЭЛИ · PvP</button></div><div class="duel-car"><img src="assets/cars/${car.id}.webp" width="320" height="200" alt="${car.model}"><b>${car.name} · КЛАСС ${cls.id}</b><span>Мощь ${build.power} · 402 м · сухой асфальт</span></div><div class="event-stats"><div><b>${p.rating}</b><small>РЕЙТИНГ</small></div><div><b>${p.wins}/${p.races}</b><small>ПОБЕДЫ</small></div><div><b>${p.best?p.best.toFixed(2):'—'}</b><small>ЛУЧШЕЕ, С</small></div></div><p class="route-note">В подборе ${data.bots} ботов и ${data.players} игроков. Соперник получает другую сборку того же класса и мощность рядом с твоей.</p><button class="primary" data-start>${readPending()?'СОХРАНИТЬ ПРОШЛЫЙ ФИНИШ':'НАЙТИ ЗАЕЗД'}</button><details class="event-rules"><summary>Правила дуэли</summary><p>Машины и тюнинг могут отличаться. Подбор держит один класс и близкую мощь, а характер машины, старт и переключения решают исход.</p><p>Боты чередуют спокойные, ровные и жёсткие заезды. Подходящая запись реального игрока тоже может попасться. Прерванная дуэль считается поражением при старте следующей.</p><p>Сервер повторяет запись заезда. Дуэли не расходуют деньги и не меняют прогресс кампании.</p></details>${data.board.length?'<div class="event-board">'+data.board.map((r,i)=>`<div class="board-row ${r.me?'is-me':''}"><b>${i+1}</b><span>${esc(r.name)} ${r.me?'· ТЫ':''}</span><strong>${r.rating}</strong></div>`).join('')+'</div>':''}`;}
 dialog.querySelector('[data-close]').onclick=()=>closeDialog(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(dialog);});
 body.onclick=async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.hasAttribute('data-retry'))return open();if(b.hasAttribute('data-campaign')){await closeDialog(dialog);document.querySelector('#race-button').click();return;}if(!b.hasAttribute('data-start'))return;busy=true;b.disabled=true;try{const saved=await flush();if(saved){toast('Прошлый результат сохранён');await open();return;}const r=await api('/start',{build:getBuild()});await closeDialog(dialog);await startRace(r.result);}catch(e){toast(e.message);if(data)render();}finally{busy=false;b.disabled=false;}};
 async function finish(ticket,inputs){const payload={ticket,inputs};pendingMemory=payload;try{localStorage.setItem('rayon-duel-pending',JSON.stringify(payload));}catch{}const r=await api('/finish',payload);clearPending(ticket);return r.result;}
 return {open,finish,flush};
}
