import {EVENT,QUESTS,PASS_REWARDS,eventLevel,dayStats,eventDay,activeEvent,league,rewardName} from './event-rules.js';
import {grantCrate} from './crates.js';
import {crateArt} from './loot-ui.js';
import {openDialog,closeDialog,animateContent} from './motion.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons=['●','⚡','★','♛'];
const person='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg>';
const icon=n=>n?icons[n]:person;
export function applyEventReceipts(save,receipts){save.eventReceipts??=[];let count=0;for(const r of receipts){if(save.eventReceipts.includes(r.id))continue;const v=r.reward;if(v.crate)grantCrate(save,v.crate,'Ивент · награда пропуска');for(const k of ['cash','hard','scrap'])if(v[k])save[k]+=v[k];save.eventReceipts.push(r.id);count++;}return count;}
export function eventMarkup(data,mode='pass'){
 const p=data.profile,now=data.now,lv=eventLevel(p),closed=!activeEvent(now),d=dayStats(p,now),days=Math.max(0,Math.ceil((EVENT.end-now)/86400000));
 const tabs=`<div class="event-tabs" role="tablist">${[['profile','ПРОФИЛЬ'],['pass','ПРОПУСК'],['leaders','ЛИДЕРЫ']].map(([id,name])=>`<button role="tab" aria-selected="${mode===id}" data-event-tab="${id}">${name}</button>`).join('')}</div>`;
 const heading=`<div class="event-season"><span>ИВЕНТ 01</span><b>${EVENT.name}</b><small>${closed?'ЗАВЕРШЁН':days+' ДН. · ДО 25 СЕНТЯБРЯ'}</small></div>`;
 if(mode==='profile')return heading+tabs+`<section class="event-profile"><div class="profile-emblem">${icon(p.avatar)}</div><h3>${esc(p.name)}</h3><span class="event-league">${league(p.score)}</span><div class="event-stats"><div><b>${data.place?'#'+data.place:'—'}</b><small>МЕСТО</small></div><div><b>${p.score}</b><small>ОЧКИ</small></div><div><b>${p.wins}/${p.races}</b><small>ПОБЕДЫ</small></div></div><label for="event-name">ПОЗЫВНОЙ</label><input id="event-name" maxlength="18" value="${esc(p.name)}" autocomplete="off" spellcheck="false"><div class="event-avatars">${icons.map((_,i)=>`<button data-avatar="${i}" aria-label="Значок ${i+1}" aria-pressed="${p.avatar===i}">${icon(i)}</button>`).join('')}</div><button class="primary" data-event-save>СОХРАНИТЬ</button><p class="event-note">Пропуск ${lv}/20 · ${p.xp} XP за ивент</p><button class="reset-progress" data-progress-reset>СБРОСИТЬ ПРОГРЕСС</button><p class="reset-progress-note">Кампания, гараж, машины и детали начнутся заново. Профиль и рейтинг дуэлей останутся.</p></section>`;
 if(mode==='leaders')return heading+tabs+`<div class="board-summary"><strong>${p.score}<small> ТВОИ ОЧКИ</small></strong><span>${data.participants} участн.</span></div><details class="event-rules"><summary>Как подняться в рейтинге</summary><p>Заезд: 50 очков. Победа: ещё 40. Каждое идеальное переключение: +15.</p><p>В зачёт идут 10 лучших заездов каждого дня. Их сумма даёт место за ивент. Заезды «на детали» дают только XP. При равных очках — одинаковое место.</p><p>Призы в конце: 1-е место — легендарный ящик; 2–10-е — эпический; остальные — ящик обвесов. Для приза нужны 10 финишей.</p><p>Сброс дня в 00:00 UTC. Новые результаты после 25 сентября не принимаются.</p></details>${data.board.length?'<div class="event-board" role="table" aria-label="Рейтинг ивента">'+data.board.map(r=>`<div role="row" class="board-row ${r.me?'is-me':''}"><b role="cell">${r.place<=3?['♛','②','③'][r.place-1]:r.place}</b><span class="board-avatar">${icon(r.avatar)}</span><span role="cell">${esc(r.name)} ${r.me?'<small>ТЫ</small>':''}</span><strong role="cell">${r.score}</strong></div>`).join('')+'</div>':'<div class="event-empty">Первый финиш — первое место.<br>В таблице появятся участники ивента.</div>'}<div class="board-self"><b>${data.place?'#'+data.place:'—'}</b><span>${esc(p.name)} · ТЫ</span><strong>${p.score}</strong></div><p class="event-note">${closed?'Итоги зафиксированы':'Сегодня зачтено '+d.best.length+'/10 · '+d.best.reduce((a,b)=>a+b,0)+' очков'}</p>${closed?`<button class="primary" data-event-claim="final" ${p.claims.includes('final')||p.races<10?'disabled':''}>${p.claims.includes('final')?'ПРИЗ ПОЛУЧЕН':p.races<10?'НУЖНО 10 ФИНИШЕЙ':'ЗАБРАТЬ ПРИЗ ИВЕНТА'}</button>`:''}`;
 return heading+tabs+`<div class="pass-progress"><strong>${lv}<small>/20</small></strong><div><b>${lv===20?'ПРОПУСК ПРОЙДЕН':p.xp%300+' / 300 XP'}</b><progress max="300" value="${lv===20?300:p.xp%300}" aria-label="Прогресс пропуска"></progress></div><span>БЕСПЛАТНО</span></div><details class="event-rules"><summary>Задания дня · до +450 XP</summary>${QUESTS.map(q=>{const done=d.claimed.includes(q.key),ready=d[q.key]>=q.target;return `<div class="quest-row"><span>${q.name}<small>${Math.min(d[q.key],q.target)}/${q.target}</small></span><button data-event-claim="quest:${eventDay(now)}:${q.key}" ${done||!ready||closed?'disabled':''}>${done?'✓':'+150 XP'}</button></div>`;}).join('')}<p>Финиш +60 XP · победа +40 · идеальное переключение +10. Задания обновляются в 00:00 UTC.</p></details><div class="pass-grid">${PASS_REWARDS.map((r,i)=>{const n=i+1,claimed=p.claims.includes('pass:'+n),ready=n<=lv,color=r.crate==='legend'?'#efbd62':r.crate==='boss'?'#c091ed':r.crate?'#79b9e6':r.hard?'#8cddba':'#bbc89e';return `<button class="pass-tile ${ready?'available':''} ${claimed?'claimed':''}" style="--reward-color:${color}" data-event-claim="pass:${n}" ${!ready||claimed?'disabled':''}><span class="pass-stage">${String(n).padStart(2,'0')}</span>${r.crate?crateArt(r.crate):'<span class="pass-resource">'+(r.cash?'₽':r.hard?'$':'⚒')+'</span>'}<b>${rewardName(r)}</b><small>${claimed?'✓ ПОЛУЧЕНО':ready?'ЗАБРАТЬ':n*300+' XP'}</small></button>`;}).join('')}</div><p class="event-note">Финал — гарантированная легендарная деталь.<br>Открытые награды можно забрать после конца ивента.</p>`;
}
export function bindEvent({save,changed,toast,sfx}){
 const dialog=document.querySelector('#event-dialog'),body=document.querySelector('#event-body');let data=null,mode='pass',busy=false,ticket=null,draftAvatar=0;
 const api=async(path='',body)=>{const response=await fetch('/api/event'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});const type=response.headers.get('content-type')||'';if(!type.includes('json'))throw Error('Ивент доступен в опубликованной игре');const result=await response.json();if(!response.ok){const error=Error(result.error||'Ивент недоступен');error.status=response.status;throw error;}return result;};
 function update(){if(!data)return;const p=data.profile,lv=eventLevel(p);document.querySelector('#profile-button').innerHTML=icon(p.avatar);document.querySelector('#event-progress').textContent=lv+'/20';document.querySelector('#event-button').classList.toggle('has-reward',p.claims.filter(k=>k.startsWith('pass:')).length<lv);if(applyEventReceipts(save,p.receipts.map(r=>({...r,id:p.id+':'+r.id}))))changed();}
 function render(){if(!dialog.open)return;animateContent(body);body.innerHTML=eventMarkup(data,mode);draftAvatar=data.profile.avatar;}
 async function sync(){data=await api();update();render();}
 async function open(next='pass'){mode=next;openDialog(dialog);if(data)render();else body.innerHTML='<p class="event-empty">Загружаем ивент…</p>';try{await sync();}catch(e){body.innerHTML='<p class="event-empty">'+esc(e.message)+'</p><button class="primary" data-event-retry>ПОВТОРИТЬ</button>';}}
 document.querySelector('#profile-button').onclick=()=>open('profile');document.querySelector('#event-button').onclick=()=>open('pass');document.querySelector('#event-close').onclick=()=>closeDialog(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(dialog);});
 body.onclick=async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.eventTab){mode=b.dataset.eventTab;render();return;}if(b.hasAttribute('data-event-retry')){await open(mode);return;}if(b.hasAttribute('data-avatar')){draftAvatar=Number(b.dataset.avatar);for(const x of body.querySelectorAll('[data-avatar]'))x.setAttribute('aria-pressed',String(x===b));return;}if(b.hasAttribute('data-progress-reset')){if(b.dataset.armed!=='true'){b.dataset.armed='true';b.textContent='ТОЧНО СБРОСИТЬ?';setTimeout(()=>{if(b.isConnected){delete b.dataset.armed;b.textContent='СБРОСИТЬ ПРОГРЕСС';}},5000);return;}const receipts=Array.isArray(save.eventReceipts)?save.eventReceipts:[];try{localStorage.setItem('rayon-drag-v2',JSON.stringify({eventReceipts:receipts}));localStorage.removeItem('rayon-drag-v1');localStorage.removeItem('rayon-duel-pending');}finally{location.reload();}return;}
 busy=true;b.disabled=true;try{let result;if(b.dataset.eventClaim){result=await api('/claim',{key:b.dataset.eventClaim});data.profile=result.profile;update();render();if(!result.result.duplicate){toast(result.result.reward?'Получено: '+rewardName(result.result.reward):'+150 XP');sfx('win');}}else if(b.hasAttribute('data-event-save')){result=await api('/profile',{name:body.querySelector('#event-name').value,avatar:draftAvatar});data.profile=result.profile;update();render();toast('Профиль сохранён');}}catch(e){toast(e.message);b.disabled=false;}finally{busy=false;}};
 async function flush(){if(!save.eventPending)return null;const result=await api('/finish',save.eventPending);save.eventPending=null;changed();if(data)data.profile=result.profile;update();return result.result;}
 async function start(practice){ticket=null;try{try{await flush();}catch(e){if(e.status===400){save.eventPending=null;changed();toast('Прошлый результат не принят: '+e.message);}else throw e;}const r=await api('/start',{practice});ticket=r.result.ticket;}catch(e){toast('Ивент: '+e.message);}}
 async function finish(result){const line=document.querySelector('#result-event');line.hidden=false;if(!ticket){line.textContent='Ивент: заезд без рейтинга';return;}save.eventPending={...result,ticket};ticket=null;changed();line.textContent='Ивент · сохраняем результат…';try{const r=await flush();line.textContent=r.duplicate?'Результат ивента сохранён':`+${r.xp} XP · +${r.score} очков${r.practice?' · тренировка':''}`;}catch(e){line.textContent='Ивент · результат ждёт отправки';toast(e.message);}}
 sync().then(flush).catch(()=>{});
 return {open,start,finish};
}
