import {rewardTiles} from './reward-tiles.js';
import {PAINT_CHANCE,paintById,PAINT_OFFERS,ownsPaint} from './paints.js';
import {DECAL_CHANCE,decalById} from './decals.js';
import {MATERIAL_PACKS} from './soft-economy.js';
import {CRATES,crateById,crateCount} from './crates.js';
import {RARITIES,partById} from './progression.js';
import {PART_OFFERS} from './shop.js';
const money=(n,c)=>n.toLocaleString('ru-RU')+(c==='hard'?' $':' ₽');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const partPicture=p=>'assets/parts/'+(['engine','gearbox'].includes(p.slot)?p.slot:p.slot==='tires'?'tires-stock':p.slot+'-'+p.rarity)+'.webp';
export const crateArt=(id,extra='')=>{const c=crateById(id);return `<span class="crate-art ${extra}" style="--cx:${c.art*25}%" aria-hidden="true"></span>`;};
const rarity=r=>`<small class="loot-rarity">${RARITIES[r].name}</small>`;
export function crateOdds(s,id){const c=crateById(id),weights=c.weights.map((w,i)=>s.pity>=7&&i<2?0:w),sum=weights.reduce((a,b)=>a+b,0);return `<details class="odds"><summary>Что внутри и шансы</summary><p>Одна деталь. ${c.type}. Повтор превращается в материалы.</p><p>Дополнительно: ${PAINT_CHANCE*100}% на новый цвет и ${DECAL_CHANCE*100}% на винил для всех машин. Собранный повтор превращается в материалы.</p><p>${weights.map((w,i)=>w?RARITIES[i].name+' '+(w/sum*100).toLocaleString('ru-RU',{maximumFractionDigits:2})+'%':'').filter(Boolean).join(' · ')}</p><p>${s.pity>=7?'Сейчас действует гарантия эпической+':'После 7 открытий без эпической — эпическая+ в следующем ящике.'}</p></details>`;}
export function ownedCrates(s){const owned=CRATES.filter(c=>crateCount(s,c.id)>0);return `<div class="loot-grid">${owned.map(c=>`<div class="loot-owned"><button class="loot-tile" data-open-box="${c.id}" style="--rarity:${RARITIES[c.rarity].color}" aria-label="Открыть ящик ${c.name}">${crateArt(c.id)}<b>${c.name}</b>${rarity(c.rarity)}<small>${c.type}</small><span class="loot-action">ОТКРЫТЬ <strong>×${crateCount(s,c.id)}</strong></span></button><button class="loot-info" data-crate-detail="${c.id}">Состав и шансы</button></div>`).join('')||'<p class="loot-empty">Ящиков пока нет</p>'}</div><button class="secondary" data-shop>В МАГАЗИН ↗</button><details class="loot-history"><summary>Откуда ящики</summary><p>5 финишей → обычный ящик.<br>Пройден район → эпический.<br>Пройдена карьера → легендарный.</p><p>За финиш — один ящик. Награда за район заменяет обычную и начинает отсчёт заново.</p>${s.lootLog.slice(0,8).map(x=>`<div><b>${crateById(x.id).name}</b><span>${esc(x.reason)}</span></div>`).join('')}</details>`;}
export function crateDetail(s,id){const c=crateById(id);return `<div class="crate-detail" style="--rarity:${RARITIES[c.rarity].color}">${crateArt(id,'hero-crate')}<h3>${c.name}</h3>${rarity(c.rarity)}<p>${c.type}</p><button class="primary" data-open-box="${id}" ${crateCount(s,id)?'':'disabled'}>ОТКРЫТЬ <span>×${crateCount(s,id)}</span></button>${crateOdds(s,id)}</div><button class="secondary" data-loot-done>НАЗАД К ЯЩИКАМ</button>`;}
export function shopMarkup(s,tab='crates'){
 const tabs=`<div class="shop-tabs">${[['crates','Ящики'],['materials','Материалы'],['power','Техника'],['body','Кузов'],['paints','Краски']].map(([id,name])=>`<button data-shop-tab="${id}" class="${tab===id?'active':''}" aria-pressed="${tab===id}">${name}</button>`).join('')}</div>`;
 const tiles=tab==='paints'?paintTiles(s):tab==='crates'?CRATES.map(c=>`<button data-offer="crate:${c.id}" class="loot-tile" style="--rarity:${RARITIES[c.rarity].color}">${crateArt(c.id)}<b>${c.name}</b>${rarity(c.rarity)}<small>${c.type}</small><span class="shop-price ${c.currency==='hard'?'hard-price':''}">${money(c.price,c.currency)}${c.cashPrice?'<small>или '+money(c.cashPrice,'cash')+'</small>':''}</span></button>`).join(''):tab==='materials'?MATERIAL_PACKS.map(p=>`<button data-offer="materials:${p.id}" class="loot-tile" style="--rarity:#a3b69a">${materialsArt()}<b>${p.name}</b><small>Материалы для любой детали</small><strong class="material-amount">+${p.amount} ⚒</strong><span class="shop-price">${money(p.price,'cash')}</span></button>`).join(''):PART_OFFERS.filter(o=>['engine','tires','gearbox'].includes(partById(o.id).slot)===(tab==='power')).map(o=>{const p=partById(o.id);return `<button data-offer="part:${p.id}" class="loot-tile part-offer" style="--rarity:${RARITIES[p.rarity].color}" ${s.inventory[p.id]?'disabled':''}><img src="${partPicture(p)}" alt="" width="180" height="120"><b>${p.nickname}</b>${rarity(p.rarity)}<small>${p.name.split(' «')[0]} · ур. 1/${p.maxRank}</small><span class="shop-price ${o.currency==='hard'?'hard-price':''}">${s.inventory[p.id]?'Уже есть':money(o.price,o.currency)}${!s.inventory[p.id]&&o.cashPrice?'<small>или '+money(o.cashPrice,'cash')+'</small>':''}</span></button>`;}).join('');
 return `${tab==='materials'?'<div class="hard-note"><b>⚒ В ДЕЛО</b><span>Материалы → уровни деталей → мощь.<br>Пакетами дешевле, чем при улучшении.</span></div>':'<div class="hard-note"><b>$ БАКСЫ</b><span>50 на старт · +5 за нового соперника · +40 за босса</span></div>'}${tabs}<div class="loot-grid">${tiles}</div><button class="secondary" data-loot-done>МОИ ЯЩИКИ</button>`;
}
const materialsArt=()=>'<svg class="materials-art" viewBox="0 0 180 120" aria-hidden="true"><defs><linearGradient id="nut-steel" x2=".8" y2="1"><stop stop-color="#d9e0d4"/><stop offset=".5" stop-color="#83958b"/><stop offset="1" stop-color="#384943"/></linearGradient></defs><path d="m49 82 38-20 49 17-36 27z" fill="#101d19"/><path d="m31 51 32-22 35 15 4 34-32 22-35-15z" fill="url(#nut-steel)" stroke="#bdc9b8" stroke-width="2"/><ellipse cx="67" cy="63" rx="15" ry="18" fill="#1c2e25" transform="rotate(18 67 63)"/><path d="m102 36 28-15 26 18-2 28-28 15-26-18z" fill="url(#nut-steel)" stroke="#bdc9b8" stroke-width="2"/><ellipse cx="128" cy="51" rx="12" ry="14" fill="#1c2e25"/><path d="m109 89 35-15 10 8-35 16z" fill="#a9bcb0"/></svg>';
const paintTiles=s=>PAINT_OFFERS.map(p=>`<button data-offer="paint:${p.id}" class="loot-tile paint-tile ${ownsPaint(s,p.id)?'owned':''}" style="--paint:${p.color};--rarity:${RARITIES[p.rarity].color}"><i class="paint-swatch"></i><b>${p.name}</b>${rarity(p.rarity)}<small>${ownsPaint(s,p.id)?'В коллекции':money(p.price,'cash')}</small></button>`).join('')+'<p class="route-note">Премиальные краски продаются только здесь и не выпадают из ящиков. Кислотный и Золото ещё дают за рекорды бонусных трасс.</p>';
export function offerMarkup(s,kind,id){if(kind==='paint'){const p=PAINT_OFFERS.find(x=>x.id===id);if(!p)return '';const owned=ownsPaint(s,id);return `<div class="crate-detail paint-detail" style="--paint:${p.color};--rarity:${RARITIES[p.rarity].color}"><i class="paint-swatch hero-swatch"></i><h3>${p.name}</h3>${rarity(p.rarity)}<p>Открывается для всех машин, ставится во вкладке «Цвет»</p>${owned?'<b>УЖЕ В КОЛЛЕКЦИИ</b>':`<button class="primary" data-buy="paint:${id}" ${s.cash<p.price?'disabled':''}>КУПИТЬ <span>${money(p.price,'cash')}</span></button>${s.cash<p.price?'<p class="shortfall">Не хватает '+money(p.price-s.cash,'cash')+'</p>':''}`}</div><button class="secondary" data-shop>НАЗАД В МАГАЗИН</button>`;}if(kind==='materials'){const p=MATERIAL_PACKS.find(x=>x.id===id);if(!p)return '';return `<div class="crate-detail">${materialsArt()}<h3>${p.name}</h3><p>+${p.amount} ⚒ для улучшения деталей</p><button class="primary" data-buy="materials:${id}" ${s.cash<p.price?'disabled':''}>КУПИТЬ <span>${money(p.price,'cash')}</span></button>${s.cash<p.price?'<p class="shortfall">Не хватает '+money(p.price-s.cash,'cash')+'</p>':''}</div><button class="secondary" data-shop>НАЗАД В МАГАЗИН</button>`;}const o=kind==='crate'?crateById(id):PART_OFFERS.find(p=>p.id===id);if(!o)return '';const item=kind==='crate'?o:partById(id),afford=s[o.currency]>=o.price;return `<div class="crate-detail" style="--rarity:${RARITIES[item.rarity].color}">${kind==='crate'?crateArt(id,'hero-crate'):`<img class="offer-part-image" src="${partPicture(item)}" alt="">`}<h3>${kind==='crate'?item.name:item.nickname}</h3>${rarity(item.rarity)}<p>${kind==='crate'?item.type:item.name.split(' «')[0]+' · конкретная деталь, уровень 1'}</p>${kind==='crate'?crateOdds(s,id):''}<button class="primary" data-buy="${kind}:${id}" ${!afford||kind==='part'&&s.inventory[id]?'disabled':''}>КУПИТЬ <span>${money(o.price,o.currency)}</span></button>${!afford?`<p class="shortfall">Не хватает ${money(o.price-s[o.currency],o.currency)}</p>`:''}${o.cashPrice?`<button class="primary cash-alternative" data-buy-cash="${kind}:${id}" ${s.cash<o.cashPrice||kind==='part'&&s.inventory[id]?'disabled':''}>ЗА РУБЛИ <span>${money(o.cashPrice,'cash')}</span></button>${s.cash<o.cashPrice?'<p class="shortfall">До покупки: '+money(o.cashPrice-s.cash,'cash')+'</p>':''}`:''}</div><button class="secondary" data-shop>НАЗАД В МАГАЗИН</button>`;}
export function paintLootCard(bonus){if(!bonus)return '';if(bonus.duplicate)return '<div class="paint-loot"><b>+10 ⚒</b><span>Коллекция цветов собрана</span></div>';const p=paintById(bonus.id);return `<div class="paint-loot" style="--paint:${p.color};--rarity:${RARITIES[p.rarity].color}"><i></i><div><small>НОВЫЙ ЦВЕТ · ${RARITIES[p.rarity].name}</small><b>${p.name}</b><span>Открыт для всех машин</span></div></div>`;}
export function decalLootCard(bonus,label='НОВАЯ ДЕКАЛЬ'){if(!bonus)return '';if(bonus.duplicate)return `<div class="paint-loot"><b>+${bonus.scrap} ⚒</b><span>Такая декаль уже есть в коллекции</span></div>`;const d=decalById(bonus.id);return `<div class="paint-loot decal-loot" style="--decal:${d.preview};--rarity:${RARITIES[d.rarity].color}"><i></i><div><small>${label} · ${RARITIES[d.rarity].name}</small><b>${d.name}</b><span>Открыта для всех машин</span></div></div>`;}
export function lootCard(drop){const p=partById(drop.id);return `<div class="loot-prize" style="--rarity:${RARITIES[p.rarity].color}"><div class="prize-rays"></div><img src="${partPicture(p)}" alt=""><small>${RARITIES[p.rarity].name}</small><h3>${p.nickname}</h3><p>${p.name.split(' «')[0]}</p>${drop.duplicate?`<b>ПОВТОР → +${drop.scrap} ⚒</b>`:'<b>НОВАЯ ДЕТАЛЬ</b>'}</div>`;}
export function crateOpening(id){const c=crateById(id);return `<div class="crate-opening" style="--rarity:${RARITIES[c.rarity].color}" role="status" aria-label="Открывается ящик ${c.name}"><div class="opening-art">${crateArt(id,'opening-closed')}${crateArt(id,'opening-open')}</div><b>${c.name}</b><small>${RARITIES[c.rarity].name}</small><span>ОТКРЫВАЕМ…</span></div>`;}
export const raceLootMarkup=result=>rewardTiles(result);
