import {DRIFT_COURSES} from './ridge-terrain.js';
// Goals consume measured travel, never frame counts or raw input. Driving straight earns no gates.
export const PARKING_ARCS=[{start:45,end:155,sign:1},{start:200,end:315,sign:-1},{start:365,end:480,sign:1},{start:540,end:670,sign:-1}];
export const PARKING_METRES=40;
export function parkingState(car){return car.parking||(car.parking={metres:[0,0,0,0],closed:[false,false,false,false],previous:car.distance||0});}
export function tickParkingCourse(car,dt,valid){const p=parkingState(car),now=car.distance,previous=p.previous;p.previous=now;if(car.crashed||car.finished)return;for(let i=0;i<4;i++){const arc=PARKING_ARCS[i],travel=Math.max(0,Math.min(now,arc.end)-Math.max(previous,arc.start));if(valid&&Math.sign(car.drift?.angle)===arc.sign&&travel<=Math.max(3,car.speed*dt*2))p.metres[i]=Math.min(PARKING_METRES,p.metres[i]+travel);if(now>=arc.end)p.closed[i]=true;}}
export const parkingCompleted=car=>parkingState(car).metres.filter(m=>m>=PARKING_METRES-.01).length;
export function parkingHint(car){const p=parkingState(car),index=PARKING_ARCS.findIndex(a=>car.distance<a.end),i=index<0?3:index,a=PARKING_ARCS[i];return {index:i,done:parkingCompleted(car),metres:Math.floor(p.metres[i]),label:index<0?'ФИНИШ':car.distance<a.start?'ДАЛЬШЕ '+(a.sign>0?'ПРАВАЯ':'ЛЕВАЯ')+' ДУГА':(a.sign>0?'ПРАВЫЙ':'ЛЕВЫЙ')+' ДРИФТ'};}
function parkingDiagram(){const keys=DRIFT_COURSES.parking.keys,points=[{x:0,y:0}];for(let d=1;d<=804;d++){let h=0;for(let i=1;i<keys.length;i++)if(d<keys[i][0]){const [a,v]=keys[i-1],[b,w]=keys[i];h=v+(w-v)*(1-Math.cos(Math.PI*(d-a)/(b-a)))*.5;break;}const last=points.at(-1);points.push({x:last.x+Math.sin(h),y:last.y-Math.cos(h)});}const xs=points.map(p=>p.x),ys=points.map(p=>p.y),loX=Math.min(...xs),loY=Math.min(...ys),w=Math.max(...xs)-loX,h=Math.max(...ys)-loY,scale=Math.min(270/w,110/h),xy=p=>[(p.x-loX)*scale+(320-w*scale)/2,(p.y-loY)*scale+10];const path=points.filter((p,i)=>i%4===0).map((p,i)=>(i?'L':'M')+xy(p).map(n=>n.toFixed(1)).join(' ')).join(' ');return `<svg viewBox="0 0 320 140" aria-label="План парковки с четырьмя последовательными дугами"><path d="${path}" fill="none" stroke="#e9b75e" stroke-width="12" opacity=".18"/><path d="${path}" fill="none" stroke="#e9b75e" stroke-width="2" stroke-dasharray="5 4"/>${PARKING_ARCS.map((a,i)=>{const [x,y]=xy(points[Math.floor((a.start+a.end)/2)]);return `<circle cx="${x}" cy="${y}" r="10" fill="#e9b75e"/><text x="${x}" y="${y+4}" text-anchor="middle" fill="#20201b" font-size="12" font-weight="bold">${i+1}</text>`;}).join('')}</svg>`;}
export function parkingBrief(){return `<div class="parking-brief"><small>ПАРКОВКА · 4 ЗАЧЁТНЫЕ ДУГИ</small>${parkingDiagram()}<b>40 м дрифта в каждой дуге</b><p>Следуй жёлтой разметке между флажками. На прямой — подруливай. На дуге — сильнее тяни бегунок в сторону поворота. Держи угол 13–50° и скорость выше 43 км/ч.</p><small>Все 4 дуги → испытание пройдено. Очки показывают качество и длину серии.</small></div>`;}
