// Generated by scripts/power-hints.mjs — recommended power per bonus track (rating units from progression.rating).
// Found by simulation: the smallest power at which a regular Samara meets the mode's condition.
export const POWER_HINTS={"overpass":235,"overpassByDistrict":[235,280,315,355,370],"overtake":275,"ridge":155};
export const powerHint=trackId=>POWER_HINTS[trackId]??null;
// Career card line: «Рекомендуемая мощь N · у тебя M», red when short.
export function powerHintText(trackId,mine){const need=powerHint(trackId);if(need==null)return '';const short=mine<need;return `<p class="power-hint ${short?'short':'ok'}">Рекомендуемая мощь <b>${need}</b> · у тебя <b>${Math.round(mine)}</b>${short?' — не хватит, качай двигатель и коробку':''}</p>`;}
