import {RARITIES,partById} from './progression.js';
import {CARS} from './fleet.js';
import {paintById} from './paints.js';
import {decalById} from './decals.js';
import {crateById} from './crates.js';
import {blueprintWord} from './car-levels.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const picture=p=>'assets/parts/'+(['engine','gearbox'].includes(p.slot)?p.slot:p.slot==='tires'?'tires-stock':p.slot+'-'+p.rarity)+'.webp';
export function rewardTile({label,value='',note='',image='',art='',rarity=0,action=''}){const tag=action?'button':'div';return `<${tag} class="reward-cell rarity-${rarity}" style="--rarity:${RARITIES[rarity]?.color||'#acb6a0'}" ${action}><div class="reward-art">${image?`<img src="${esc(image)}" alt="">`:art||`<strong>${esc(value)}</strong>`}</div>${label?`<b>${esc(label)}</b>`:''}${image||art?`<strong>${esc(value)}</strong>`:''}</${tag}>`;}
function partTile(drop){if(!drop)return '';const p=partById(drop.id);return rewardTile({label:p.nickname,image:picture(p),rarity:p.rarity,note:drop.duplicate?'':RARITIES[p.rarity].name+' · новая деталь'});}
function colourTile(bonus,decal=false){if(!bonus)return '';if(bonus.duplicate)return rewardTile({label:'Материалы',value:'+'+(bonus.scrap||10)+' ⚒',note:decal?'Повтор винила':'Повтор краски'});const p=decal?decalById(bonus.id):paintById(bonus.id);return rewardTile({label:p.name,rarity:p.rarity,note:decal?'Винил · все машины':'Краска · все машины',art:`<i class="reward-swatch" style="background:${esc(decal?p.preview:p.color)}"></i>`});}
export function rewardTiles(result){let cells='';for(const [key,symbol] of [['cash','₽'],['scrap','⚒'],['hard','$']])if(result[key]>0)cells+=rewardTile({label:'',value:'+'+result[key].toLocaleString('ru-RU')+'\u00a0'+symbol,note:key==='scrap'&&result.convertedShards?'Включая '+result.convertedShards+' лишних '+blueprintWord(result.convertedShards):''});cells+=partTile(result.drop)+colourTile(result.bonusPaint)+colourTile(result.bonusDecal,true)+colourTile(result.bossDecal,true);const s=result.carShard;if(s?.amount)cells+=rewardTile({label:CARS[s.index].name,image:'assets/cars/'+CARS[s.index].id+'-blueprint.webp',value:'+'+s.amount+'\u00a0'+blueprintWord(s.amount),note:s.unlocked?'Машина открыта':s.pending?'Собрана · нужно место в гараже':s.current+' из '+s.needed});for(const [i,c] of (result.crates||[]).entries()){if(c.opened){cells+=partTile(c.opened)+colourTile(c.opened.bonusPaint)+colourTile(c.opened.bonusDecal,true);continue;}const box=crateById(c.id);cells+=rewardTile({label:'Открыть ящик',rarity:box.rarity,action:`data-earned-crate="${i}"`,art:`<span class="crate-art" style="--cx:${box.art*25}%"></span>`});}return cells?`<div class="reward-grid" aria-label="Полученные награды">${cells}</div>`:'';}
