import * as T from 'three';
import {FrameProfiler} from './frame-profiler.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
for(const id of ['revision','weather','camera','quality'])if(params.has(id))$(id).value=params.get(id);
const revision=$('revision').value,base=revision==='current'?'/':`/__rev/${revision}/`;
const [{createGLTFLoader},{createRaceWorld,scrollRaceScenery},{WeatherEffects},{CARS},{applyCustomization},{GameRenderer,outdoorEnvironment,captureEnvironment,shadowBudget},{QUALITY},{attachGroundLight},{finishCameraFrame}]=await Promise.all(['gltf.js','race-world.js','weather-effects.js','fleet.js','car-customization.js','pbr-renderer.js','render-quality.js','ground-light.js','finish-camera.js'].map(p=>import(base+p)));
// Deterministic effects and identical simulation samples in each run, regardless of FPS.
let seed=701;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);Math.random=random;
const renderer=new T.WebGLRenderer({antialias:false});document.body.append(renderer.domElement);renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;
const graphics=new GameRenderer(renderer),camera=new T.PerspectiveCamera(46,390/844,.1,300),mode=$('weather').value,qi=+$('quality').value;
let errors=0;renderer.debug.onShaderError=(gl,p,v,f)=>{errors++;console.error(gl.getProgramInfoLog(p),gl.getShaderInfoLog(v),gl.getShaderInfoLog(f));};
function roadTexture(){const size=512,data=new Uint8Array(size*size*4);for(let i=0;i<size*size;i++){const v=61+random()*22;data[i*4]=v;data[i*4+1]=v+2;data[i*4+2]=v-8;data[i*4+3]=255;}const t=new T.DataTexture(data,size,size);Object.assign(t,{generateMipmaps:true,minFilter:T.LinearMipmapLinearFilter,magFilter:T.LinearFilter,anisotropy:4,wrapS:T.RepeatWrapping,wrapT:T.RepeatWrapping,colorSpace:T.SRGBColorSpace});t.repeat.set(3,70);t.needsUpdate=true;return t;}
const factory=params.get('track')==='factory';
if(factory&&['current','02cd44e'].includes(revision))await (await import(base+'industrial-kit.js')).loadIndustrialKit();
const trackConfig=factory?{...(await import(base+'tracks.js')).TRACKS[1],environmentState:mode==='night'?'night':'day',weatherState:mode==='night'?'rain':'dry'}:null;
const road=roadTexture(),world=createRaceWorld(factory?1:mode==='night'?4:0,{roadTexture:road,...(trackConfig?{look:trackConfig}:{})}),scene=world.scene,environment=outdoorEnvironment(renderer,world.cfg);const bg=scene.background;scene.background=environment.texture;const probe=captureEnvironment(renderer,scene,new T.Vector3(-1.9,1.1,-2));scene.background=bg;scene.environment=probe.texture;renderer.toneMappingExposure=world.cfg.night?1.16:1;
const cars=[],models=[];
for(let i=0;i<2;i++){const meta=CARS[i],car=(await createGLTFLoader().loadAsync('/assets/race-cars/'+meta.id+'.glb')).scene,root=new T.Group();car.userData.fit=meta;Object.assign(root.userData,{racing:true,carLength:meta.length,carWidth:meta.width,wheelbase:meta.wheelbase,axleOffset:meta.axleOffset,wheelRadius:meta.radius});root.add(car);applyCustomization(root,car,{},i?'ivory':'cherry');root.rotation.y=-Math.PI/2;root.position.set(i?1.9:-1.9,0,i?-2:0);root.userData.tailMaterials=[];
 car.traverse(o=>{if(!o.isMesh)return;o.castShadow=o.receiveShadow=true;if(/headlight/i.test(o.material.name)){o.material.emissive.set(0xffdfaa);o.material.emissiveIntensity=world.cfg.night?2.2:.12;}if(/^Red lens/.test(o.material.name)){o.material.emissive.set(0xff2010);o.material.emissiveIntensity=world.cfg.night?.65:.1;root.userData.tailMaterials.push(o.material);}});
 const light=attachGroundLight(root,meta,{ambient:world.cfg.night?1:.26});light.setBeam(world.cfg.night?1:0);light.setTail(world.cfg.night?.8:.15);scene.add(root);models.push(root);cars.push({speed:18,travelDistance:0,time:0,gear:3,levels:[3,1,1],finished:true});}
const smokeData=new Uint8Array(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const i=(y*32+x)*4;smokeData[i]=smokeData[i+1]=smokeData[i+2]=255;smokeData[i+3]=Math.max(0,1-Math.hypot((x-16)/16,(y-16)/16))**2*255;}const smoke=new T.DataTexture(smokeData,32,32);smoke.needsUpdate=true;
const weather=new WeatherEffects(scene,{...world.cfg,storm:0},true,smoke);weather.setQuality(QUALITY[qi]);shadowBudget(scene.userData.sun,QUALITY[qi]);
// Fixed phone-sized render workload, independent of the desktop window. This is NOT iPhone hardware.
const width=390,height=844;graphics.resize(width,height,3,qi,QUALITY[qi]);
let frameIndex=0,paused=false,last=0,bench=null,shadows=true,mirrors=true;
function positionFrame(index){const time=index/60,travel=time*18;if(scrollRaceScenery)scrollRaceScenery(world.moving,travel);else for(const r of world.moving){r.obj.position.z=((r.start+travel+270)%r.span+r.span)%r.span-270;r.obj.visible=r.obj.position.z>-285&&r.obj.position.z<125;}scene.userData.start.position.z=-3+travel;scene.userData.tree.position.z=-6+travel;scene.userData.finish.position.z=scene.userData.finishRival.position.z=-405+travel;world.update(travel);for(const c of cars){c.time=time;c.travelDistance=travel;}for(const m of models)m.userData.groundLight.setHeight(0);weather.update(params.has('still')?0:1/60,...cars,...models);
 const cm=$('camera').value;if(cm==='race'){camera.position.set(2,12,21);camera.up.set(0,1,0);camera.lookAt(0,0,2);camera.fov=46;}else{const t=cm==='tracking'?Number(params.get('filmTime')||2.6):cm==='hero'?6.1:time%7;const f=finishCameraFrame(t,{x:-1.9,width:1.65,height:1.4,length:4.006},Number(params.get('side')||1));camera.position.set(f.position.x,f.position.y,f.position.z);camera.up.set(Math.sin(f.roll),Math.cos(f.roll),0);camera.lookAt(f.target.x,f.target.y,f.target.z);camera.fov=f.fov;}camera.updateProjectionMatrix();}
positionFrame(0);scene.userData.raceShadows?.update(scene,camera);await renderer.compileAsync(scene,camera);
const controls=['run','soak','pause','shadows','mirrors','revision','weather','camera','quality'];
const carMirrorsAvailable=!!scene.userData.wetRoad&&scene.userData.wetRoad.mirror.enabled!==false;
if(!carMirrorsAvailable){mirrors=false;$('mirrors').textContent='Копии машин: нет';}
const lockControls=locked=>{for(const id of controls)$(id).disabled=locked||(id==='mirrors'&&!carMirrorsAvailable);};lockControls(false);
const gpuTimerAvailable=!!renderer.getContext().getExtension('EXT_disjoint_timer_query_webgl2');
function start(seconds){if(bench)return;weather.reset();frameIndex=0;seed=701;$('result').textContent='';bench={seconds,started:performance.now(),warm:90,frames:0,profiler:new FrameProfiler(renderer),windows:[],checkpoint:{}};lockControls(true);paused=false;$('pause').textContent='Пауза';}
function finish(){const p=bench.profiler,summary=p.summary();p.dispose();const result={revision,weather:mode,camera:$('camera').value,quality:QUALITY[qi].name,width:graphics.target.width,height:graphics.target.height,seconds:bench.seconds,shadows,mirrors,shaderErrors:errors,userAgent:navigator.userAgent,...summary,windows:bench.windows,notes:['CPU = JS update plus render submission, not GPU execution.','Frame intervals include browser scheduling.','Fixed 390×844 CSS workload with DPR 3 capped by profile; not physical iPhone.','Simulation advances by 1/60 per rendered frame; this isolates rendering, not full gameplay/HUD/audio.','Windows contain consecutive 300-frame blocks; not cumulative.','Still-frame override: '+(params.get('still')??'off')]};$('result').textContent=JSON.stringify(result,null,2);document.querySelector('details').open=true;$('status').textContent=`ГОТОВО · CPU ${summary.cpuSubmitMs.median}/${summary.cpuSubmitMs.p95} мс · GPU ${summary.gpuMs.median??'недоступен'} · кадр ${summary.frameIntervalMs.median}/${summary.frameIntervalMs.p95} мс · ${summary.drawCalls.median} draw calls`;bench=null;lockControls(false);paused=true;$('pause').textContent='Продолжить';}
$('run').onclick=()=>start(20);$('soak').onclick=()=>start(600);$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Продолжить':'Пауза';};
$('shadows').onclick=()=>{shadows=!shadows;scene.userData.sun.castShadow=shadows;scene.traverse(o=>{for(const m of [].concat(o.material||[]))m.needsUpdate=true;});$('shadows').textContent='Тени: '+(shadows?'вкл':'выкл');};
$('mirrors').onclick=()=>{mirrors=!mirrors;if(scene.userData.wetRoad)scene.userData.wetRoad.mirror.group.visible=mirrors;$('mirrors').textContent='Отражения: '+(mirrors?'вкл':'выкл');};
for(const id of ['revision','weather','camera','quality'])$(id).onchange=()=>{const q=new URLSearchParams();if(factory)q.set('track','factory');if(params.has('mobile'))q.set('mobile',params.get('mobile'));for(const k of ['revision','weather','camera','quality'])q.set(k,$(k).value);location.search=q;};
function frame(t){requestAnimationFrame(frame);if(document.hidden){if(bench){bench.profiler.dispose();bench=null;lockControls(false);$('status').textContent='Замер отменён: вкладка скрыта';}last=0;return;}const interval=last?t-last:0;last=t;if(paused)return;
 const measure=bench&&bench.warm<=0;if(measure)bench.profiler.begin();positionFrame(params.has('still')?Number(params.get('still')):frameIndex);frameIndex++;graphics.render(scene,camera);if(measure){bench.profiler.end(renderer.info.render,interval);bench.frames++;if(bench.frames%300===0){bench.windows.push({frame:bench.frames,elapsedSeconds:+((performance.now()-bench.started)/1000).toFixed(1),...bench.profiler.summary(bench.checkpoint)});bench.checkpoint=bench.profiler.counts();}if(performance.now()-bench.started>bench.seconds*1000){finish();return;}}else if(bench&&--bench.warm===0)bench.started=performance.now();
 if(frameIndex%30===0)$('status').textContent=`${revision} · ${mode} · ${graphics.target.width}×${graphics.target.height} · ${renderer.info.render.calls} draws · ошибок ${errors}${bench?' · замер '+Math.floor((performance.now()-bench.started)/1000)+' с':''} · GPU timer ${gpuTimerAvailable}`;
}
requestAnimationFrame(frame);
